language: node_js
sudo: required
node_js: static

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "Sibylau"
  - git config user.email "sibylau@outlook.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle
