# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - hexo
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "Sibylau"
- git config --global user.email "sibylau@outlook.com"
- npm install -g hexo-cli
install:
# 不用yarn的话这里改成 npm i 即可
- npm install hexo-deployer-git --save
- npm i
script:
- hexo clean
- hexo g
after_success:
#- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 GH_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$GH_TOKEN@github.com/Sibylau/Sibylau.github.io.git master:master
- hexo d